sudo: required  # required for docker
services:
    - docker  # install a copy of docker

before_install:
    - docker build -t patrickcmd/docker-react-course -f Dockerfile.dev .

script:
    - docker run -e CI=true patrickcmd/docker-react-course yarn run test -- --coverage